### ISSUE TITLE
IRKIT-iOS-SDKにてうまくコンパイルできない件

### ISSUE THREAD

**Issue by naokibizen** [irkit/ios-sdk#3]
こんにちは。IRKITを使ってみたいと思いSDKをダンロードし、コンパイルしてみたのですがうまくいかず（Undefined symbols 、linker command failed）、質問させてください。

初めてお問い合わせします。よろしくお願い致します。
　
XCODEからのエラーメッセージ。

Undefined symbols for architecture x86_64:

  "_OBJC_CLASS_$_ISHTTPOperation", referenced from:
      _OBJC_CLASS_$_IRHTTPJSONOperation in libIRKit.a(IRHTTPJSONOperation.o)
  "_OBJC_CLASS_$_ISHTTPOperationQueue", referenced from:
      _OBJC_CLASS_$_IRHTTPOperationQueue in libIRKit.a(IRHTTPOperationQueue.o)
  "_OBJC_METACLASS_$_ISHTTPOperation", referenced from:
      _OBJC_METACLASS_$_IRHTTPJSONOperation in libIRKit.a(IRHTTPJSONOperation.o)
  "_OBJC_METACLASS_$_ISHTTPOperationQueue", referenced from:
      _OBJC_METACLASS_$_IRHTTPOperationQueue in libIRKit.a(IRHTTPOperationQueue.o)
ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

XCODEでの上記エラー表示
<img width="582" alt="errors" src="https://cloud.githubusercontent.com/assets/1555007/12108438/3b5e3486-b3bb-11e5-9a4a-33991eb7e466.png">

XCODE での様子
<img width="405" alt="xcode" src="https://cloud.githubusercontent.com/assets/1555007/12108443/4a1c9044-b3bb-11e5-8122-166ab81ded08.png">

以上です。

**Comment by mash** [comment]
こちらでも同じ問題を確認できました。
調べます。。

**Comment by mash** [comment]
こちらのコミットで対応しました。
https://github.com/irkit/ios-sdk/commit/551a1b0084ac9ff8192b406b8282c72b2245f3a5

最新のソースコードに更新し `pod install`を行った後、再度お試しいただけますか？

**Comment by naokibizen** [comment]
ビルドとデバイスでのインストール実行を確認できました！
ありがとうございました！

**Comment by mash** [comment]
:+1:
