### ISSUE TITLE
ios-sdk 1.0.1をcocoapods経由でアプリに入れてストア申請したらITMS-90535が表示された

### ISSUE THREAD

**Issue by tichise** [irkit/ios-sdk#4]
1.0.1を含めたら、アプリストア申請時に下記のようなエラーが出るようになりました。古いバージョンでは問題有りませんでした。

![image](https://cloud.githubusercontent.com/assets/43707/15730275/27d784a2-28a6-11e6-82cc-b665a1f31ceb.png)

解決方法を教えていただけると助かります。あと最新版のsdkをpodから落とせるようにしていただきたいです。

#### エラー理由
これのようです。
http://qiita.com/roworks/items/c745b8c0b3f9efd4d546

**Comment by mash** [comment]
確認します！

**Comment by tichise** [comment]
ver 2.3.0をcocoapodsで落とせないので、1.0.1でアプリとIRKitの連携を試しましたが、何度やっても1.0.1だとWifi設定後のグルグル画面で失敗します。

cocoapodsで2.3.0を落とせないので、carthageで2.3.0をビルドしようとしましたがcarthageだと途中でビルドに失敗しました。

何度もすみませんが、cocoapodsから2.3.0を落とせるように修正をお願いします。

**Comment by mash** [comment]
修正しました。
3.0.1 でお試しいただけませんか

**Comment by tichise** [comment]
確認します。対応有難うございます。

**Comment by tichise** [comment]
アプリ申請通りました。ありがとうございます。

**Comment by tichise** [comment]
@mash アプリ無事リリース出来ました。

http://bit.ly/29PELxx
